apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodetest
  name: nodetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodetest
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: task-pv-storage
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: app-data
